/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import Model.Doctor;

/**
 *
 * @author sujithkaluva
 */
public class DoctorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkArea
     */
    Doctor doctor;
    public DoctorWorkArea(Doctor dObj) {
        initComponents();
        doctor = dObj;
        doctorName.setText(doctor.getFirstName()+" "+doctor.getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        logOutAdmin = new javax.swing.JButton();
        appointmentsBtn = new javax.swing.JButton();
        encounterHistory = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doctorName = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        logOutAdmin.setBackground(new java.awt.Color(204, 204, 204));
        logOutAdmin.setForeground(new java.awt.Color(0, 0, 0));
        logOutAdmin.setText("Logout");
        logOutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutAdminActionPerformed(evt);
            }
        });

        appointmentsBtn.setBackground(new java.awt.Color(255, 255, 204));
        appointmentsBtn.setForeground(new java.awt.Color(0, 0, 0));
        appointmentsBtn.setText("Appointments");
        appointmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentsBtnActionPerformed(evt);
            }
        });

        encounterHistory.setBackground(new java.awt.Color(255, 255, 204));
        encounterHistory.setForeground(new java.awt.Color(0, 0, 0));
        encounterHistory.setText("Encounters");
        encounterHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(appointmentsBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(encounterHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(appointmentsBtn)
                .addGap(18, 18, 18)
                .addComponent(encounterHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(logOutAdmin)
                .addGap(21, 21, 21))
        );

        mainPanel.setLeftComponent(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hello,");

        doctorName.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        doctorName.setForeground(new java.awt.Color(0, 51, 102));
        doctorName.setText("Doctor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(doctorName))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorName)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        mainPanel.setRightComponent(jPanel3);

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel)
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutAdminActionPerformed
        // TODO add your handling code here:

        Home home = new Home();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        home.setVisible(true);
    }//GEN-LAST:event_logOutAdminActionPerformed

    private void appointmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentsBtnActionPerformed
        // TODO add your handling code here:
        AppointmentDoctor aptDctr = new AppointmentDoctor(doctor);
        mainPanel.setRightComponent(aptDctr);
    }//GEN-LAST:event_appointmentsBtnActionPerformed

    private void encounterHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterHistoryActionPerformed
        // TODO add your handling code here:
        ViewEncounterdoctor enDctr = new ViewEncounterdoctor(doctor);
        mainPanel.setRightComponent(enDctr);
    }//GEN-LAST:event_encounterHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentsBtn;
    private javax.swing.JLabel doctorName;
    private javax.swing.JButton encounterHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logOutAdmin;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JSplitPane mainPanel;
    // End of variables declaration//GEN-END:variables
}
