/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

/**
 *
 * @author sujithkaluva
 */
public class createEmployee extends javax.swing.JPanel {

    /**
     * Creates new form createEmployee
     */
    public createEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createEmpLabel = new javax.swing.JLabel();
        mainLabel = new javax.swing.JLabel();
        empNameLabel = new javax.swing.JLabel();
        empIdLabel = new javax.swing.JLabel();
        empAgeLabel = new javax.swing.JLabel();
        empStartDateLabel = new javax.swing.JLabel();
        empGenderLabel = new javax.swing.JLabel();
        empLevelLabel = new javax.swing.JLabel();
        empTeamInfoLabel = new javax.swing.JLabel();
        empPositionTitleLabel = new javax.swing.JLabel();
        contactInfoLabel = new javax.swing.JLabel();
        empEmailIdLabel = new javax.swing.JLabel();
        empPhnNumLabel = new javax.swing.JLabel();
        empPhotoLabel = new javax.swing.JLabel();
        uploadImageBtn = new javax.swing.JButton();
        createEmpBtn = new javax.swing.JButton();
        empNameTxt = new javax.swing.JTextField();
        empIdTxt = new javax.swing.JTextField();
        empAgeTxt = new javax.swing.JTextField();
        empLevelTxt = new javax.swing.JTextField();
        empGenderBox = new javax.swing.JComboBox<>();
        empTeamInfoTxt = new javax.swing.JTextField();
        empPositionTitleTxt = new javax.swing.JTextField();
        empEmailTxt = new javax.swing.JTextField();
        empPhoneTxt = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        createEmpLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        createEmpLabel.setForeground(new java.awt.Color(255, 255, 255));
        createEmpLabel.setText("Create Employee");

        mainLabel.setBackground(new java.awt.Color(255, 255, 255));
        mainLabel.setFont(new java.awt.Font("Charter", 0, 18)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainLabel.setText("Employee Management System");

        empNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        empNameLabel.setText("Name");

        empIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        empIdLabel.setText("Employee ID");

        empAgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        empAgeLabel.setText("Age");

        empStartDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        empStartDateLabel.setText("Start Date");

        empGenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        empGenderLabel.setText("Gender");

        empLevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        empLevelLabel.setText("Level");

        empTeamInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        empTeamInfoLabel.setText("Team Info");

        empPositionTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        empPositionTitleLabel.setText("Position Title");

        contactInfoLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        contactInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactInfoLabel.setText("Contact Information");

        empEmailIdLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        empEmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        empEmailIdLabel.setText("Email Id");

        empPhnNumLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        empPhnNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        empPhnNumLabel.setText("Phone Number");

        empPhotoLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        empPhotoLabel.setForeground(new java.awt.Color(255, 255, 255));
        empPhotoLabel.setText("Photo");

        uploadImageBtn.setBackground(new java.awt.Color(0, 153, 204));
        uploadImageBtn.setForeground(new java.awt.Color(255, 255, 255));
        uploadImageBtn.setText("Upload Image");

        createEmpBtn.setBackground(new java.awt.Color(0, 153, 204));
        createEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        createEmpBtn.setText("Create");
        createEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmpBtnActionPerformed(evt);
            }
        });

        empNameTxt.setBackground(new java.awt.Color(255, 255, 255));
        empNameTxt.setForeground(new java.awt.Color(0, 0, 0));
        empNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameTxtActionPerformed(evt);
            }
        });

        empIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        empIdTxt.setForeground(new java.awt.Color(0, 0, 0));
        empIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIdTxtActionPerformed(evt);
            }
        });

        empAgeTxt.setBackground(new java.awt.Color(255, 255, 255));
        empAgeTxt.setForeground(new java.awt.Color(0, 0, 0));
        empAgeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empAgeTxtActionPerformed(evt);
            }
        });

        empLevelTxt.setBackground(new java.awt.Color(255, 255, 255));
        empLevelTxt.setForeground(new java.awt.Color(0, 0, 0));
        empLevelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empLevelTxtActionPerformed(evt);
            }
        });

        empGenderBox.setBackground(new java.awt.Color(255, 255, 255));
        empGenderBox.setForeground(new java.awt.Color(0, 0, 0));
        empGenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        empTeamInfoTxt.setBackground(new java.awt.Color(255, 255, 255));
        empTeamInfoTxt.setForeground(new java.awt.Color(0, 0, 0));
        empTeamInfoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTeamInfoTxtActionPerformed(evt);
            }
        });

        empPositionTitleTxt.setBackground(new java.awt.Color(255, 255, 255));
        empPositionTitleTxt.setForeground(new java.awt.Color(0, 0, 0));
        empPositionTitleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPositionTitleTxtActionPerformed(evt);
            }
        });

        empEmailTxt.setBackground(new java.awt.Color(255, 255, 255));
        empEmailTxt.setForeground(new java.awt.Color(0, 0, 0));
        empEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empEmailTxtActionPerformed(evt);
            }
        });

        empPhoneTxt.setBackground(new java.awt.Color(255, 255, 255));
        empPhoneTxt.setForeground(new java.awt.Color(0, 0, 0));
        empPhoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPhoneTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(createEmpLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(createEmpBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(contactInfoLabel)
                                        .addComponent(empPhnNumLabel)
                                        .addComponent(empEmailIdLabel)
                                        .addComponent(empPhotoLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(empIdLabel)
                                            .addComponent(empNameLabel)
                                            .addComponent(empAgeLabel)
                                            .addComponent(empGenderLabel)
                                            .addComponent(empStartDateLabel)
                                            .addComponent(empLevelLabel)
                                            .addComponent(empTeamInfoLabel)
                                            .addComponent(empPositionTitleLabel))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uploadImageBtn)
                                    .addComponent(empNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empLevelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empGenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empTeamInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empPositionTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(mainLabel)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createEmpLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameLabel)
                    .addComponent(empNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIdLabel)
                    .addComponent(empIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empAgeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empGenderLabel)
                    .addComponent(empGenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empStartDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empLevelLabel)
                    .addComponent(empLevelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empTeamInfoLabel)
                    .addComponent(empTeamInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPositionTitleLabel)
                    .addComponent(empPositionTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(contactInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPhnNumLabel)
                    .addComponent(empPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empEmailIdLabel)
                    .addComponent(empEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPhotoLabel)
                    .addComponent(uploadImageBtn))
                .addGap(18, 18, 18)
                .addComponent(createEmpBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEmpBtnActionPerformed

    private void empNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameTxtActionPerformed

    private void empIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdTxtActionPerformed

    private void empAgeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empAgeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empAgeTxtActionPerformed

    private void empLevelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empLevelTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empLevelTxtActionPerformed

    private void empTeamInfoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTeamInfoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTeamInfoTxtActionPerformed

    private void empPositionTitleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPositionTitleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPositionTitleTxtActionPerformed

    private void empEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empEmailTxtActionPerformed

    private void empPhoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPhoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPhoneTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactInfoLabel;
    private javax.swing.JButton createEmpBtn;
    private javax.swing.JLabel createEmpLabel;
    private javax.swing.JLabel empAgeLabel;
    private javax.swing.JTextField empAgeTxt;
    private javax.swing.JLabel empEmailIdLabel;
    private javax.swing.JTextField empEmailTxt;
    private javax.swing.JComboBox<String> empGenderBox;
    private javax.swing.JLabel empGenderLabel;
    private javax.swing.JLabel empIdLabel;
    private javax.swing.JTextField empIdTxt;
    private javax.swing.JLabel empLevelLabel;
    private javax.swing.JTextField empLevelTxt;
    private javax.swing.JLabel empNameLabel;
    private javax.swing.JTextField empNameTxt;
    private javax.swing.JLabel empPhnNumLabel;
    private javax.swing.JTextField empPhoneTxt;
    private javax.swing.JLabel empPhotoLabel;
    private javax.swing.JLabel empPositionTitleLabel;
    private javax.swing.JTextField empPositionTitleTxt;
    private javax.swing.JLabel empStartDateLabel;
    private javax.swing.JLabel empTeamInfoLabel;
    private javax.swing.JTextField empTeamInfoTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton uploadImageBtn;
    // End of variables declaration//GEN-END:variables
}
