/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import employeeDetails.EmployeeProfile;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sujithkaluva
 */
public class searchEmployee extends javax.swing.JPanel {

    /**
     * Creates new form searchEmployee
     */
    ArrayList<EmployeeProfile> employeeList = new ArrayList<EmployeeProfile>(List.copyOf(createEmployee.employeeList));
    EmployeeProfile searchedEmployee;
    public searchEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        searchEmpLabel = new javax.swing.JLabel();
        empIdLabel = new javax.swing.JLabel();
        searchIdField = new javax.swing.JTextField();
        searchEmpBtn = new javax.swing.JButton();
        empIdTxt = new javax.swing.JTextField();
        empAgeTxt = new javax.swing.JTextField();
        empLevelTxt = new javax.swing.JTextField();
        empGenderBox = new javax.swing.JComboBox<>();
        empTeamInfoTxt = new javax.swing.JTextField();
        empPositionTitleTxt = new javax.swing.JTextField();
        empEmailTxt = new javax.swing.JTextField();
        empNameLabel = new javax.swing.JLabel();
        empPhoneTxt = new javax.swing.JTextField();
        empIdLabel1 = new javax.swing.JLabel();
        empAgeLabel = new javax.swing.JLabel();
        empStartDateLabel = new javax.swing.JLabel();
        empGenderLabel = new javax.swing.JLabel();
        empStartDatePicker = new com.toedter.calendar.JDateChooser();
        empLevelLabel = new javax.swing.JLabel();
        empTeamInfoLabel = new javax.swing.JLabel();
        empPositionTitleLabel = new javax.swing.JLabel();
        contactInfoLabel = new javax.swing.JLabel();
        empEmailIdLabel = new javax.swing.JLabel();
        empPhnNumLabel = new javax.swing.JLabel();
        empNameTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        updateEmployeeBtn = new javax.swing.JButton();
        deleteEmpBtn = new javax.swing.JButton();

        searchPanel.setBackground(new java.awt.Color(51, 51, 51));
        searchPanel.setForeground(new java.awt.Color(255, 255, 255));

        searchEmpLabel.setBackground(new java.awt.Color(51, 51, 51));
        searchEmpLabel.setFont(new java.awt.Font("Charter", 0, 18)); // NOI18N
        searchEmpLabel.setForeground(new java.awt.Color(204, 204, 0));
        searchEmpLabel.setText("Search Employee");

        empIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        empIdLabel.setText("Enter Employee ID :");

        searchIdField.setBackground(new java.awt.Color(255, 255, 255));
        searchIdField.setForeground(new java.awt.Color(0, 0, 0));

        searchEmpBtn.setBackground(new java.awt.Color(0, 153, 204));
        searchEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchEmpBtn.setText("Search");
        searchEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpBtnActionPerformed(evt);
            }
        });

        empIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        empIdTxt.setForeground(new java.awt.Color(0, 0, 0));
        empIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIdTxtActionPerformed(evt);
            }
        });

        empAgeTxt.setBackground(new java.awt.Color(255, 255, 255));
        empAgeTxt.setForeground(new java.awt.Color(0, 0, 0));
        empAgeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empAgeTxtActionPerformed(evt);
            }
        });

        empLevelTxt.setBackground(new java.awt.Color(255, 255, 255));
        empLevelTxt.setForeground(new java.awt.Color(0, 0, 0));
        empLevelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empLevelTxtActionPerformed(evt);
            }
        });

        empGenderBox.setBackground(new java.awt.Color(255, 255, 255));
        empGenderBox.setForeground(new java.awt.Color(0, 0, 0));
        empGenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        empTeamInfoTxt.setBackground(new java.awt.Color(255, 255, 255));
        empTeamInfoTxt.setForeground(new java.awt.Color(0, 0, 0));
        empTeamInfoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTeamInfoTxtActionPerformed(evt);
            }
        });

        empPositionTitleTxt.setBackground(new java.awt.Color(255, 255, 255));
        empPositionTitleTxt.setForeground(new java.awt.Color(0, 0, 0));
        empPositionTitleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPositionTitleTxtActionPerformed(evt);
            }
        });

        empEmailTxt.setBackground(new java.awt.Color(255, 255, 255));
        empEmailTxt.setForeground(new java.awt.Color(0, 0, 0));
        empEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empEmailTxtActionPerformed(evt);
            }
        });

        empNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        empNameLabel.setText("Name");

        empPhoneTxt.setBackground(new java.awt.Color(255, 255, 255));
        empPhoneTxt.setForeground(new java.awt.Color(0, 0, 0));
        empPhoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPhoneTxtActionPerformed(evt);
            }
        });

        empIdLabel1.setForeground(new java.awt.Color(255, 255, 255));
        empIdLabel1.setText("Employee ID");

        empAgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        empAgeLabel.setText("Age");

        empStartDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        empStartDateLabel.setText("Start Date");

        empGenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        empGenderLabel.setText("Gender");

        empStartDatePicker.setBackground(new java.awt.Color(255, 255, 255));
        empStartDatePicker.setForeground(new java.awt.Color(0, 0, 0));

        empLevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        empLevelLabel.setText("Level");

        empTeamInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        empTeamInfoLabel.setText("Team Info");

        empPositionTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        empPositionTitleLabel.setText("Position Title");

        contactInfoLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        contactInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactInfoLabel.setText("Contact Information");

        empEmailIdLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        empEmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        empEmailIdLabel.setText("Email Id");

        empPhnNumLabel.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        empPhnNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        empPhnNumLabel.setText("Phone Number");

        empNameTxt.setBackground(new java.awt.Color(255, 255, 255));
        empNameTxt.setForeground(new java.awt.Color(0, 0, 0));
        empNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameTxtActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        updateEmployeeBtn.setBackground(new java.awt.Color(0, 153, 204));
        updateEmployeeBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateEmployeeBtn.setText("Update Employee");

        deleteEmpBtn.setBackground(new java.awt.Color(0, 153, 204));
        deleteEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteEmpBtn.setText("Delete Employee");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empNameLabel)
                            .addComponent(empAgeLabel)
                            .addComponent(empGenderLabel)
                            .addComponent(empStartDateLabel)
                            .addComponent(empLevelLabel)
                            .addComponent(empTeamInfoLabel))
                        .addGap(41, 41, 41)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empNameTxt)
                            .addComponent(empAgeTxt)
                            .addComponent(empLevelTxt)
                            .addComponent(empTeamInfoTxt)
                            .addComponent(empGenderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empStartDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(empPositionTitleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(empPositionTitleTxt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(searchPanelLayout.createSequentialGroup()
                                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(empPhnNumLabel)
                                                .addComponent(empEmailIdLabel))
                                            .addGap(18, 18, 18)
                                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(empEmailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                                .addComponent(empPhoneTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                                        .addComponent(contactInfoLabel)
                                        .addComponent(deleteEmpBtn))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(116, 116, 116))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, searchPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(empIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(searchIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(searchEmpBtn))
                            .addComponent(searchEmpLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap(408, Short.MAX_VALUE)
                        .addComponent(empIdLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(empIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateEmployeeBtn)
                .addGap(372, 372, 372))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(searchEmpLabel)
                .addGap(25, 25, 25)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIdLabel)
                    .addComponent(searchIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEmpBtn))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameLabel)
                    .addComponent(empNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIdLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empAgeLabel)
                    .addComponent(empPositionTitleLabel)
                    .addComponent(empPositionTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empGenderLabel)
                            .addComponent(empGenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empStartDateLabel)
                            .addComponent(empStartDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empLevelLabel)
                            .addComponent(empLevelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empTeamInfoLabel)
                            .addComponent(empTeamInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(contactInfoLabel)
                        .addGap(17, 17, 17)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empPhnNumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empEmailIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEmployeeBtn)
                    .addComponent(deleteEmpBtn))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empAgeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empAgeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empAgeTxtActionPerformed

    private void empLevelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empLevelTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empLevelTxtActionPerformed

    private void empTeamInfoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTeamInfoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTeamInfoTxtActionPerformed

    private void empPositionTitleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPositionTitleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPositionTitleTxtActionPerformed

    private void empEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empEmailTxtActionPerformed

    private void empPhoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPhoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPhoneTxtActionPerformed

    private void empNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameTxtActionPerformed

    private void empIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdTxtActionPerformed

    private void searchEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpBtnActionPerformed
        // TODO add your handling code here:
        String empId = searchIdField.getText();
        //emps=getEmployeeDetails();
        boolean recordFound = false;
        for (EmployeeProfile emp : employeeList) {
            if (String.valueOf(emp.getEmpId()).equals(empId)) {
                searchedEmployee = emp;
                empNameTxt.setText(emp.getEmpName());
                empIdTxt.setText(emp.getEmpId());
                empAgeTxt.setText(String.valueOf(emp.getEmpAge()));
                empGenderBox.setSelectedItem(emp.getEmpGender());
                empStartDatePicker.setDate(emp.getStartDate());
                empLevelTxt.setText(emp.getLevel());
                empTeamInfoTxt.setText(emp.getTeamInfo());
                empPositionTitleTxt.setText(emp.getPositionTitle());
                empPhoneTxt.setText(emp.getCellNumber());
                empEmailTxt.setText(emp.getEmailId());
                
                /*
                BufferedImage photo = ImageIO.read(new ByteArrayInputStream(emp.getPhoto()));
                JFrame viewImgFrame = new JFrame();
                ImageIcon icon = new ImageIcon(photo);
                JLabel label = new JLabel(icon);
                viewImgFrame.add(label);
                viewImgFrame.pack();
                viewImgFrame.setVisible(true);
                */
                recordFound = true;
                break;
            }

        }
        if (!recordFound) {
            JOptionPane.showMessageDialog(this, "Record not found");
            
            empNameTxt.setText("");
            empIdTxt.setText("");
            empAgeTxt.setText("");
            empStartDatePicker.setDate(null);
            empLevelTxt.setText("");
            empTeamInfoTxt.setText("");
            empPositionTitleTxt.setText("");
            empPhoneTxt.setText("");
            empEmailTxt.setText("");
            empGenderBox.setSelectedItem(null);
        }
    }//GEN-LAST:event_searchEmpBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            BufferedImage photo = ImageIO.read(new ByteArrayInputStream(searchedEmployee.getPhoto()));
            JFrame viewImgFrame = new JFrame();
            ImageIcon icon = new ImageIcon(photo);
            JLabel label = new JLabel(icon);
            viewImgFrame.add(label);
            viewImgFrame.pack();
            viewImgFrame.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(searchEmployee.class.getName()).log(Level.SEVERE, "Error in Displaying Image", ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactInfoLabel;
    private javax.swing.JButton deleteEmpBtn;
    private javax.swing.JLabel empAgeLabel;
    private javax.swing.JTextField empAgeTxt;
    private javax.swing.JLabel empEmailIdLabel;
    private javax.swing.JTextField empEmailTxt;
    private javax.swing.JComboBox<String> empGenderBox;
    private javax.swing.JLabel empGenderLabel;
    private javax.swing.JLabel empIdLabel;
    private javax.swing.JLabel empIdLabel1;
    private javax.swing.JTextField empIdTxt;
    private javax.swing.JLabel empLevelLabel;
    private javax.swing.JTextField empLevelTxt;
    private javax.swing.JLabel empNameLabel;
    private javax.swing.JTextField empNameTxt;
    private javax.swing.JLabel empPhnNumLabel;
    private javax.swing.JTextField empPhoneTxt;
    private javax.swing.JLabel empPositionTitleLabel;
    private javax.swing.JTextField empPositionTitleTxt;
    private javax.swing.JLabel empStartDateLabel;
    private com.toedter.calendar.JDateChooser empStartDatePicker;
    private javax.swing.JLabel empTeamInfoLabel;
    private javax.swing.JTextField empTeamInfoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton searchEmpBtn;
    private javax.swing.JLabel searchEmpLabel;
    private javax.swing.JTextField searchIdField;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton updateEmployeeBtn;
    // End of variables declaration//GEN-END:variables
}
